// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub implementation for GPU stats support

package proto

// GPUDevice represents a GPU device
type GPUDevice struct {
	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type         string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Memory       uint64 `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	ComputeUnits int32  `protobuf:"varint,5,opt,name=compute_units,json=computeUnits,proto3" json:"compute_units,omitempty"`
	Available    bool   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
}

// MinerInfo represents miner information
type MinerInfo struct {
	MinerId   string `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Hostname  string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

// RegistrationResponse represents registration response
type RegistrationResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MinerId string `protobuf:"bytes,3,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
}

// WorkRequest represents work request
type WorkRequest struct {
	MinerId string `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
}

// WorkResponse represents work response
type WorkResponse struct {
	BlockIndex   int64  `protobuf:"varint,1,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	PreviousHash string `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Data         string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Difficulty   int32  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Timestamp    int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

// WorkSubmission represents work submission
type WorkSubmission struct {
	MinerId    string `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	BlockIndex int64  `protobuf:"varint,2,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	Nonce      int64  `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash       string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

// SubmissionResponse represents submission response
type SubmissionResponse struct {
	Accepted bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reward   int64  `protobuf:"varint,3,opt,name=reward,proto3" json:"reward,omitempty"`
}

// MinerStatus represents miner status with GPU support
type MinerStatus struct {
	MinerId            string        `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	HashRate           int64         `protobuf:"varint,2,opt,name=hash_rate,json=hashRate,proto3" json:"hash_rate,omitempty"`
	BlocksMined        int64         `protobuf:"varint,3,opt,name=blocks_mined,json=blocksMined,proto3" json:"blocks_mined,omitempty"`
	CpuUsagePercent    float64       `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	TotalHashes        int64         `protobuf:"varint,5,opt,name=total_hashes,json=totalHashes,proto3" json:"total_hashes,omitempty"`
	MiningTimeSeconds  int64         `protobuf:"varint,6,opt,name=mining_time_seconds,json=miningTimeSeconds,proto3" json:"mining_time_seconds,omitempty"`
	GpuDevices         []*GPUDevice  `protobuf:"bytes,7,rep,name=gpu_devices,json=gpuDevices,proto3" json:"gpu_devices,omitempty"`
	GpuHashRate        int64         `protobuf:"varint,8,opt,name=gpu_hash_rate,json=gpuHashRate,proto3" json:"gpu_hash_rate,omitempty"`
	GpuEnabled         bool          `protobuf:"varint,9,opt,name=gpu_enabled,json=gpuEnabled,proto3" json:"gpu_enabled,omitempty"`
	HybridMode         bool          `protobuf:"varint,10,opt,name=hybrid_mode,json=hybridMode,proto3" json:"hybrid_mode,omitempty"`
}

// HeartbeatResponse represents heartbeat response
type HeartbeatResponse struct {
	Active  bool   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

// StopResponse represents stop response
type StopResponse struct {
	Success          bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalBlocksMined int64  `protobuf:"varint,3,opt,name=total_blocks_mined,json=totalBlocksMined,proto3" json:"total_blocks_mined,omitempty"`
}

// NOTE: In production, this file would be generated by:
// protoc --go_out=. --go_opt=paths=source_relative \
//        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//        proto/mining.proto
//
// For now, this stub provides the necessary types for GPU support
